strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: 100
# --------------------------------------
# Dataset parameters
# --------------------------------------
dataset_name: jhmdb
split: 1
n_inter: 2
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: adamw
lr: 0.0001
weight_decay: 0.001
momentum: 0.9
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: cosine
warmup_lr: 0.000001
min_lr: 0.00001
warmup_epochs: 20
# --------------------------------------
# Segmentation Model parameters
# --------------------------------------
seg_model_name: unet
seg_type: resnet50
seg_pretrained: True
num_joints: 15
# --------------------------------------
# Flow Model parameters
# --------------------------------------
flow_model_name: raft
flow_model_path: /home/zpengac/RAFT/models/raft-sintel.pth
global_flow: True
dataset: sintel
small: False
# --------------------------------------
# Point Head parameters
# --------------------------------------
POINT_HEAD_NUM_FC: 3
POINT_HEAD_FC_DIM: 256
POINT_HEAD_TRAIN_NUM_POINTS: 128
POINT_HEAD_SUBDIVISION_STEPS: 3
POINT_HEAD_SUBDIVISION_NUM_POINTS: 784
IMPLICIT_POINTREND_IMAGE_FEATURE_ENABLED: True
IMPLICIT_POINTREND_POS_ENC_ENABLED: True
ROI_MASK_HEAD_OUTPUT_SIDE_RESOLUTION: 14
ROI_MASK_HEAD_FC_DIM: 512
ROI_MASK_HEAD_NUM_FC: 2
ROI_MASK_HEAD_CONV_DIM: 256
ROI_MASK_HEAD_IN_FEATURES: 512
ROI_MASK_HEAD_POOLER_RESOLUTION: 14
# --------------------------------------
# Model Head parameters
# --------------------------------------
corr_levels: 4
corr_radius: 4
hidden_dim: 128
sf_dim: 256
# --------------------------------------
# Loss parameters
# --------------------------------------
gamma: 0.8
thres_con: 0.9
n_iters: 12
w_body: 1.0
w_joint: 1.0
w_flow: 1.0
w_consist: 10.0
w_weak: 0.01
alpha_lr: 1.0
alpha_group: 0.2
# Body loss
w_neg_body: 1.0
w_unsup_body: 1.0
# Joint loss
w_neg_joint: 5.0
# --------------------------------------
# Augmentation parameters
# --------------------------------------
input_size: [224, 224]
# Random crop
p_crop: 0.5
# Color jitter
brightness: 0.2
contrast: 0.2
saturation: 0.2
hue: 0.1
p_jitter: 0.5
# Blur
kernel_size: 3
sigma: 0.1
p_blur: 0.5