strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: 200
# --------------------------------------
# Dataset parameters
# --------------------------------------
dataset_name: jhmdb
split: 1
n_inter: 2
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: adamw
lr: 0.00001
weight_decay: 0.001
momentum: 0.9
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: cosine
warmup_lr: 0.000001
min_lr: 0.00001
warmup_epochs: 20
# --------------------------------------
# Segmentation Model parameters
# --------------------------------------
seg_model_name: segmenter
patch_size: 16
n_layers_encoder: 12
n_layers_decoder: 2
d_model: 384
n_heads: 6
seg_out_channels: 17
dropout: 0.1
drop_path_rate: 0.1
variant: vit_small_patch16_224
# --------------------------------------
# Flow Model parameters
# --------------------------------------
flow_model_name: raft
flow_model_path: /home/zpengac/RAFT/models/raft-sintel.pth
global_flow: True
dataset: sintel
small: False
# --------------------------------------
# Loss parameters
# --------------------------------------
gamma: 0.8
thres_con: 0.9
n_iters: 12
w_body: 1.0
w_joint: 1.0
w_flow: 1.0
w_consist: 100.0
# --------------------------------------
# Augmentation parameters
# --------------------------------------
input_size: [224, 224]
# Color jitter
brightness: 0.4
contrast: 0.4
saturation: 0.4
hue: 0.1
p_jitter: 0.5
# Blur
kernel_size: 3
sigma: 0.1
p_blur: 0.5